name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore AutomagicWorkflows
    - name: Build
      run: dotnet build AutomagicWorkflows --configuration Release --no-restore
    - name: Test
      run: dotnet test AutomagicWorkflows --no-restore --verbosity normal
    - name: Publish
      run: |
        dotnet nuget source Add -Name "GitHub" -Source "https://nuget.pkg.github.com/RossNordby/scratchpad/index.json" -UserName RossNordby
        dotnet pack "AutomagicWorkflows/SomeLibrary/" -c Release
        dotnet nuget push "AutomagicWorkflows/SomeLibrary/bin/Release/SomeLibrary.1.0.0.nupkg" -k "${{ secrets.GITHUB_TOKEN }}" -s "GitHub"
